name: Java CI with Maven and Docker

on:
  push:
    branches: ["main"]
  pull_request:
    branches:
      - "main"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: cache maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
              ${{ runner.os }}-maven-

      - name: Build with Maven (and generate coverage)
        run: mvn clean verify --no-transfer-progress

      - name: Build Docker image
        run: docker build -t usermanagement-service .

      - name: Check if JaCoCo report exists
        run: |
          echo "Checking for jacoco.xml..."
          ls -lh target/site/jacoco
          cat target/site/jacoco/jacoco.xml | head -n 10

      - name: Run SonarQube analysis
        run: mvn sonar:sonar -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}